### ISSUE TITLE
valgrind errors when running test_dataset

### ISSUE THREAD

**Issue by yzanhua** [hpc-io/vol-cache#16]
## Summary
When running the [tests](https://github.com/hpc-io/vol-cache/tree/develop/tests)/test_dataset.cpp testcase, valgrind reported some memory errors including "Invalid read of size 4", "Invalid write of size 8", "memory leak", etc.

## How to reproduce:
```shell
% echo $HDF5_VOL_CONNECTOR
cache_ext config=cache_1.cfg;under_vol=512;under_info={under_vol=0;under_info={}}

% make checkmem
HDF5_CACHE_WR=yes \
mpirun -n 2 \
valgrind --log-file=v-%p.txt --leak-check=full --track-origins=yes \
./test
****HDF5 Testing Dataset*****
=============================================
 Buf dim: 2048 x 2048
   nproc: 2
=============================================
Creating file parallel_file.h5
Creating group 0
Creating dataset dset_test
Writing dataset dset_test
------- EXT CACHE VOL DATASET Write
------- EXT CACHE VOL DATASET Write
Closing dataset dset_test
Closing group 0
Closing file parallel_file.h5
====================
```
## Valgrind output files
Below are the valgrind output files from two MPI processes.
[v-252365.txt](https://github.com/hpc-io/vol-cache/files/9587102/v-252365.txt)
[v-252366.txt](https://github.com/hpc-io/vol-cache/files/9587104/v-252366.txt)

**Comment by zhenghh04** [comment]
I found out that this is caused by too large HDF5_CACHE_WRITE_BUFFER_SIZE. Please reduce that and try again.
